name: Basic-linux
on:
  workflow_dispatch: null
jobs:
  my-job: # Provide a valid name for your job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display information
        run: |
          ls
          ls -la
          date
          cat /etc/os-release
